name: Deploy Package to PyPi Test Repo
on:
  push:
    branches:
      - package

jobs:
  check-for-new-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.filter.outputs.version }}
    steps: 
      - uses: actions/checkout@v2

      - name: Determine New version
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            version:
              - 'pyproject.toml'

  create-and-deploy-package:
    needs: check-for-new-version
    if: ${{ needs.check-for-new-version.outputs.version == 'true' }}
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install PyPi Package Upload Dependencies
        run: |
          python3 -m pip install --upgrade build
          python3 -m pip install --upgrade twine

      - name: Build Package
        run: python3 -m build

      - name: TEST Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: PROD Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PROD_PYPI_API_KEY }}          
          repository_url:  https://upload.pypi.org/legacy/